workflows:
    Build-IPA:
        name: Build IPA
        max_build_duration: 120
        instance_type: mac_mini_m1
        artifacts:
        - **
publishing:
  email: 
     recipients:
         - davidjohnson297@yahoo.com
         - davidjohnson4648@aol.com
     notify:
          success: true 
          failure: true 
