workflows:
    Build-IPA:
        name: Build IPA
        max_build_duration: 120
        instance_type: mac_mini_m1
        artifacts:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - flutter_drive.log
        - ios.yaml
        - swift.yaml
        - objective-c-xcode.yaml
publishing:
  email: IDK
     recipients:
         - davidjohnson297@yahoo.com
         - davidjohnson4648@aol.com
     notify:
          success: true 
          failure: true 
